void TBDkp(TBD *w);
void TBDdr(TBD *w);
void TBDcl();
int TBD3mnd(TBD *w);
void TBD3ftc(TBDtb *cache);
TBD *TBD3fls(TBD *w);
void TBD3und(TBDtb *cache);
void TBD3uls(TBD *w);
extern TBD* TBDomg=NULL;;
extern TBD* TBDtau=NULL;;
extern TBDtb *TBDttb=NULL;;
extern TBDtb *TBDctb=NULL;;
extern TBDtv *TBDvtb=NULL;;
void TBD0ntl();
TBD *TBD0dtc(TBDtb *TBDttb,TBD *w);
int TBDrc(TBD *w);
TBD *TBD0gtc(TBDtb *TBDctb,int x,TBD *a,TBD *b);
TBD *TBD0dnc(TBDtb *nc,TBD *w);
void TBD0rtc(TBDtb *cache,TBD *f());
void TBD0rls(TBDtb *newcache,TBD *w,TBD *f());
TBD *TBD0cnd(int x,TBD *a,TBD *b,TBD *c);
TBD *TBD0crn(int x,TBD *a,TBD *b,TBD *c);
TBD *ORG_TBD0crn(int x,TBD *a,TBD *b,TBD *c);
TBD *TBDng(TBD *s);
TBD *TBDcn(TBD *s,TBD *t);
TBD *TBDbs(int x,TBD *w);
int TBDtr(TBD *s);
int TBD2ccs(TBD *s,TBD *t);
TBD *TBD2crs(TBD* r0,int x,int v);
TBD *TBD2ctb(TBD *w);
int TBD2cml(TBD *w);
TBD *TBDds(TBD *s,TBD *t);
TBD *TBDxb(int x,TBD *s);
int TBDmp(TBD *s);
void TBDvl(char **vlist);
TBD *TBDvr(char *var);
TBD *TBD1clt(int a);
void TBD1svl(char **a,int *b,int l,int r) /* increasing */;
int TBD1snm(char *s,char **a,int *b,int l,int r);
void TBDrl(char **vlist);
TBD *TBDrn(TBD *w);
typedef struct _TBDtv { int count; int *ival; int *rtab; char **name; } TBDtv; ;
typedef struct _TBDtb { int tablesz; int nodes; int cap; TBD **table; } TBDtb;;
TBD* TBDomg;;
TBD* TBDtau;;
TBDtb *TBDttb;;
TBDtb *TBDctb;;
TBDtv *TBDvtb;;
void TBD0ntl();;
TBD *TBD0dtc(TBDtb *TBDttb,TBD *w);;
TBD *TBD0gtc(TBDtb *TBDctb,int x,TBD *a,TBD *b);;
TBD *TBD0dnc(TBDtb *nc,TBD *w);;
void TBD0rtc(TBDtb *cache,TBD *f());;
void TBD0rls(TBDtb *newcache,TBD *w,TBD *f());;
TBD *TBD0cnd(int x,TBD *a,TBD *b,TBD *c);;
TBD *TBD0crn(int x,TBD *a,TBD *b,TBD *c);;
TBD *TBD1clt(int a);;
void TBD1svl(char **a,int *b,int l,int r);;
int TBD1snm(char *s,char **a,int *b,int l,int r);;
int TBD2ccs(TBD *s,TBD *t);;
TBD *TBD2crs(TBD* r0,int x,int v);;
TBD *TBD2ctb(TBD *w);;
int TBD2cml(TBD *w);;
int TBD3mnd(TBD *w);;
void TBD3ftc(TBDtb *cache);;
TBD *TBD3fls(TBD *w);;
void TBDvl(char **vlist);
TBD *TBDvr(char *var);
TBD *TBDng(TBD *s);
TBD *TBDcn(TBD *s,TBD *t);
TBD *TBDbs(int x,TBD *w);
int TBDtr(TBD *s);
void TBDkp(TBD *w);
void TBDdr(TBD *w);
void TBDcl();
void TBDrl(char **vlist);
TBD *TBDrn(TBD *w);
int TBDrc(TBD *w);
TBD *TBDds(TBD *s,TBD *t);
TBD *TBDxb(int x,TBD *s);
int TBDmp(TBD *s);
void TBD0ntl();
TBD *TBD0dtc(TBDtb *TBDttb,TBD *w);
TBD *TBD0gtc(TBDtb *TBDctb,int x,TBD *a,TBD *b);
TBD *TBD0dnc(TBDtb *nc,TBD *w);
void TBD0rtc(TBDtb *cache,TBD *f());
void TBD0rls(TBDtb *newcache,TBD *w,TBD *f());
TBD *TBD0cnd(int x,TBD *a,TBD *b,TBD *c);
TBD *TBD0crn(int x,TBD *a,TBD *b,TBD *c);
TBD *TBD1clt(int a);
void TBD1svl(char **a,int *b,int l,int r) ;
int TBD1snm(char *s,char **a,int *b,int l,int r);
int TBD2ccs(TBD *s,TBD *t);
TBD *TBD2crs(TBD* r0,int x,int v);
TBD *TBD2ctb(TBD *w);
int TBD2cml(TBD *w);
int TBD3mnd(TBD *w);
void TBD3ftc(TBDtb *cache);
TBD *TBD3fls(TBD *w);
