int COIapply(tree *prog,int pp) ;
void O2mvar(tree *list);
void O2mtable(tree *list);
void O2mtable0(tree *t0,int *left);
int O2var2int(char *s);
void O2add2left(int *ll,int a);
void O2mtable1(tree *t0,int *left);
void O2mtable1add(int *tabi,tree *t0);
void O2mvarcore(tree *t0);
void O2reachableanalysis();
void O2mtable2init(tree *t0);
void O2mtable2inita(tree *t0,tree *t1);
void O2mtable2initaa(int *tabi,tree *t1);
void O2simplify(tree *t0);
tree *O2simplify1(tree *l0,int i);
tree *O2simplify2(tree *t0,tree *vl);
tree *O2simplify3(tree *l0,tree *vl);
int O2inlist(int i) ;
int O2someninlist(tree *t0,tree *vl) ;
int COTSinall(tree *t0,tree *vl,tree *vv,tree *vv1,workspace *ws1);
int COTSinv(tree *t0,tree *vlist) ;
int COTSinitdis(tree *t0,workspace *ws1) ;
int COTSindependence(tree *t0,tree *vv,tree *vv1) ;
void COTSvar(tree *start,tree *middle,tree *next,tree *vv,tree *vv1) ;
tree *COTScond(tree *l0,tree *v0) ;
tree *COTSassleft(tree *t0,tree *v0) ;
tree *COTSassright(tree *t0,tree *v0) ;
int COTSinleft(tree *t0,tree *vl);
int COTSinrightleft(tree *t0,tree *vl);
int COTSinrightright(tree *t0,tree *vl);
int COTSintersection(tree *v1,tree *v2);
int COTSsimplify(workspace *ws1,tree *dbpr);
tree *COTSsimplify3(tree *l0,tree *la,tree *lend,tree *vl,tree *vv,tree *vv1,tree *init,workspace *ws1);
int COTSrem(tree *t0,tree *la,tree *lend,tree *init,workspace *ws1) ;
tree *trtr(tree *t1,tree *t2);
void trtr0(tree *t1,tree *t2);
int trtr1(tree *t1,tree *t2);
tree *COTSclean(tree *l0,tree *dbp);
int COTSremok(tree *t0,tree *ty,tree *la,tree *lend,tree *init,workspace *ws1);
int FOimp(tree *t1,tree *t2,tree *prog,int nb,tree *constr);
model *FOspec2model(tree *spec,tree *prog,int booln,int auxp);
int FOsat(tree *spec,tree *prog,int booln,tree *propcs);
int FOapply(char *solver,model *mo);
