extern int gSELflag;;
extern FILE *gLog;;
int simpbranching(qinfo *qi);
int qbranching(int f0,qinfo *qi,qcdata *cd,int *clen);
int qbranchingea(int e,int f0,qinfo *qi,qcdata *cd,int *clen);
int qbranchingdc(int d,int f0,qinfo *qi,qcdata *cd,int *clen);
int *qinitorder(qinfo *qi,int *clen);
float ev0(qinfo *qi,int *clen,int literal);
int lookuplist(int rt,qinfo *qi,int *clist);
int LUqunitp(int rt,qinfo *qi,int *clen,int *cur);
int LUqunitprop1(qinfo *qi,int rt,int neg,int c,sdata *sd,qcdata *cd,int *clen,int *cure,char *gim);
int LUqunitprop0(qinfo *qi,int rt,int c0,int val,qcdata *cd,int *clen,int *cure,char *gim);
int LUqunitgetliteral(qinfo *qi,int c0,qcdata *cd,int *clen,char *gim);
int QBFapply(qinfo *qi,qmdata *qm);
extern int gSELflag;;
int sel(int rt,int *var,qinfo *qi,int *clen);
int sel_ev0(int rt,int *var,qinfo *qi,int *clen);
int sel_ev1(int rt,int *var,qinfo *qi,int *clen);
int seldc(int *var,qinfo *qi,int *clen);
