tree *eqstate(int pa,int i,int pb,int j,int k);
tree *eqpath(int pa,int k);
tree *constructeq(int a,int b,tree *vars,int bn);
tree *actlreplaceeq(tree *t,tree *vars,int bn);
int fkxy(tree *t,int k,int lpath);
int gkxy(tree *t,int k,int lpath);
int fkx(tree *t,int k);
int gkx(tree *t,int k);
int formulatype(tree *t);
tree *treetr(tree *tr,int a,int b,int pn);
tree *addnumber(tree *t,int i);
tree *addnumberconditional(tree *t,int i,int c);
void cnfwrite(int *mstring,int mstringc);
void cnfwritestring(int *mstring,int mstringc,model *mo);
void conv2write(int *s1,int *s2,int n,int a1,int a2,int b1,int b2,int bn,int aux1,int auxp);
model *conv2model(tree *init,tree *trans,tree *spec,int bn,int k,int auxp);
tree *spec2f1(tree *spec,int bn,int k,tree *vars,tree *tr);
tree *spec2f0(tree *spec,int bn,int k,tree *vars,tree *tr);
model *convmodel(tree *init,tree *trans,tree *spec,int bn,int k,int npath);
model *convmodelspec(tree *spec,int auxp);
model *concatmodel(model *m1,model *m2);
tree *actl2f1a(tree *t,int k,int pn,int pa,int x,int y);
tree *actl2f1(tree *t,int k,tree *vars,int pn);
tree *actl2f0a(tree *t,int k,int pn,int pa,int x,int y);
tree *actl2f0(tree *t,int k,tree *vars,int pn);
int convmodel_one1(tree *t,char c,int s0,int s,int *mstring);
int convmodel_one2(tree *t,char c,int s,int *mstring);
int f2cnf(tree *t,char c,int s0,int auxp,int *mstring);
int iscclause(tree *t) ;
tree *lcnfcombine(tree *t1,tree *t2);
int lcnf(tree *t);
tree *makeform_ll(tree *f(),tree *t,int k,int i,int j,char c,int pn);
tree *ltl2f1(tree *t,int k,int i,int pn);
tree *makeform_l0(tree *f(),tree *t,int k,int i,int j,char c,int pn,int ll);
tree *ltl2f0b(tree *t,int k,int i,int pn,int ll,int j);
tree *ltl2f0(tree *t,int k,int lstart,int pn,tree *tr);
tree *makeform_ll(tree *f(),tree *t,int k,int i,int j,char c,int pn);
tree *ltl2f1(tree *t,int k,int i,int pn);
