model *cnfcreate(tree *prog,tree *spec,tree *cs,int booln,int k,int pv,int ptt);
model *cnfcreatet0(tree *prog,tree *cs,int booln,int k);
model *cnfcreateall(tree *prog,tree *spec,tree *cs,int booln,int k,int pv);
int sat(tree *prog,tree *spec,tree *cs,int booln,int k,int pv,int ptt);
int cnfsat(tree *prog,tree *spec,tree *cs,int booln,int k,int pv,int ptt,char *s);
tree *agTRUE();
tree *afagTRUE();
tree *agagTRUE();
int applysolver(char *fn,model *mo,char *mnsat);
extern int PAR_deb;
tree *file2prog(char *fn);
tree *progreconstruct(tree *prog);
tree *csconstruct(tree *prog);
tree *ndlockconstruct(tree *prog);
tree *prog2bool(tree *prog,int booln);
tree *cs2bool(tree *spec,tree *prog,int booln);
tree *specs(tree *prog,pginfo *pgi,int pt,int pp);
int reverse_1(int x,int bn,int m);
int reverse_2(int x,int aux1a,int n);
void reverse(int *s1,int n1,int bn,int m,int n);
model *cnfcreate(tree *prog,tree *spec,tree *cs,int booln,int k,int pv,int ptt);
model *cnfcreatet0(tree *prog,tree *cs,int booln,int k);
model *cnfcreateall(tree *prog,tree *spec,tree *cs,int booln,int k,int pv);
int sat(tree *prog,tree *spec,tree *cs,int booln,int k,int pv,int ptt);
int cnfsat(tree *prog,tree *spec,tree *cs,int booln,int k,int pv,int ptt,char *s);
int applysolver(char *fn,model *mo,char *mnsat);
extern int PAR_deb;
tree *file2prog(char *fn);
tree *progreconstruct(tree *prog);
tree *csconstruct(tree *prog);
tree *ndlockconstruct(tree *prog);
tree *prog2bool(tree *prog,int booln);
tree *cs2bool(tree *spec,tree *prog,int booln);
tree *specs(tree *prog,pginfo *pgi,int pt,int pp);
int reverse_1(int x,int bn,int m);
void reverse(int *s1,int n1,int bn,int m,int n);
