float utiltime(int finish);
char *file2string(FILE *f);
void writeintlist(int *ss,int a,int b,FILE *g);
void writecharlist(char *ss,int a,int b,FILE *g);
void quicksort_ab(int *a,int *b,int l,int r ) /* decreasing */;
void quicksort_abf(float *a,int *b,int l,int r) /* decreasing */;
void cnfwritemodel(model *mo,FILE *g);
void modelcompress(model *mm,mstruct *cc,mdata *wc,int *cl);
model *file2model(char *fn);
void read_numbers(char *ll,model *mm);
void read_clauses(char *ll,model *mm);
int remove_red(int *p0,int k);
int remove_red2(int *p0);
void modelclean(model *mm);
void modelcompresseq(model *mm,mstruct *cc,mdata *wc,int *cl,int *n1,int *n2);
int intin(int a,int *b,int x,int y);
int eqcycle(int *a,int *b);
char *stringsearch(char *s,char *a);
void stringedone(char *s,char *a,char *b);
void stringreplace(char *s,char *a,char *b);
